export type PermissionKey =
  | 'PATIENT_REGISTER'
  | 'ANC_VITALS_WRITE'
  | 'ANC_VALIDATE'
  | 'PRESCRIPTION_WRITE'
  | 'REFERRAL_CREATE'
  | 'BED_MANAGE'
  | 'BLOOD_REQUISITION'
  | 'LAB_RESULT_WRITE'
  | 'DRUG_DISPENSE'
  | 'TRIP_NAVIGATE'
  | 'DISTRICT_ANALYTICS'
  | 'PATIENT_SELF_VIEW'
  | 'STAFF_MANAGE';

export const ROLE_PERMISSIONS: Record<string, PermissionKey[]> = {
  ASHA_WORKER: ['PATIENT_REGISTER', 'ANC_VITALS_WRITE', 'REFERRAL_CREATE'],
  ANM: ['PATIENT_REGISTER', 'ANC_VITALS_WRITE', 'ANC_VALIDATE', 'REFERRAL_CREATE'],
  DOCTOR: [
    'PATIENT_REGISTER', 
    'ANC_VITALS_WRITE', 
    'ANC_VALIDATE', 
    'PRESCRIPTION_WRITE', 
    'REFERRAL_CREATE', 
    'BED_MANAGE', 
    'BLOOD_REQUISITION'
  ],
  HOSPITAL_ADMIN: ['BED_MANAGE', 'BLOOD_REQUISITION', 'STAFF_MANAGE'],
  DISTRICT_OFFICER: ['DISTRICT_ANALYTICS', 'STAFF_MANAGE'],
  PATIENT: ['PATIENT_SELF_VIEW'],
  FAMILY: ['PATIENT_SELF_VIEW'],
  LAB_TECH: ['LAB_RESULT_WRITE'],
  PHARMACIST: ['DRUG_DISPENSE'],
  AMBULANCE_DRIVER: ['TRIP_NAVIGATE'],
  SUPER_ADMIN: [
    'PATIENT_REGISTER', 
    'ANC_VITALS_WRITE', 
    'ANC_VALIDATE', 
    'PRESCRIPTION_WRITE', 
    'REFERRAL_CREATE', 
    'BED_MANAGE', 
    'BLOOD_REQUISITION', 
    'LAB_RESULT_WRITE', 
    'DRUG_DISPENSE', 
    'TRIP_NAVIGATE', 
    'DISTRICT_ANALYTICS', 
    'PATIENT_SELF_VIEW', 
    'STAFF_MANAGE'
  ]
};
