export interface CdssInputVitals {
  systolicBp: number;
  diastolicBp: number;
  hbLevel: number;
  weightKg: number;
  gestationalAgeWeeks: number;
  urineProtein?: string;
  randomBloodSugar?: number;
}

export interface CandidateHospital {
  facilityId: string;
  facilityNameEn: string;
  facilityTier: string;
  distanceKm: number;
  travelTimeMins: number;
  hduBedsAvailable: number;
  bloodStock: Record<string, number>;
}

export const evaluateCdss = (vitals: CdssInputVitals, candidateHospitals: CandidateHospital[] = []) => {
  const { systolicBp, diastolicBp, hbLevel, weightKg, gestationalAgeWeeks, urineProtein = 'Nil', randomBloodSugar = 100 } = vitals;

  // 1. Data Completeness & Prediction Reliability Evaluation
  let presentInputs = 0;
  if (systolicBp && diastolicBp) presentInputs++;
  if (hbLevel) presentInputs++;
  if (weightKg) presentInputs++;
  if (gestationalAgeWeeks) presentInputs++;
  if (urineProtein) presentInputs++;
  if (randomBloodSugar) presentInputs++;

  const completenessPercent = Math.round((presentInputs / 6) * 100);
  const isCoreMissing = !systolicBp || !hbLevel;

  const predictionReliability = isCoreMissing
    ? 'INSUFFICIENT_DATA'
    : completenessPercent >= 83
    ? 'HIGH'
    : completenessPercent >= 60
    ? 'MEDIUM'
    : 'LOW';

  // Mandatory Clinical Disclaimer
  const disclaimer =
    'This recommendation is generated by the JANANI360 Clinical Decision Support System based on available clinical data and standard maternal healthcare guidelines (WHO / GOI / Karnataka Health Dept). Final clinical decisions and prescriptions must always be taken by an authorized medical professional.';

  if (isCoreMissing) {
    return {
      status: 'INSUFFICIENT_DATA',
      dataCompletenessPercent: completenessPercent,
      predictionReliability: 'INSUFFICIENT_DATA',
      disclaimer,
      reasons: ['Core vitals missing (Blood Pressure or Hemoglobin level). Score calculation paused.'],
      actionPlan: {
        immediateWithin30Mins: 'Perform immediate blood pressure and hemoglobin test using Point-of-Care Hb meter.'
      }
    };
  }

  // 2. Specialized Clinical Engine Calculations
  const triggeredGuidelines: Array<{ guideline: string; rule: string; reason: string }> = [];
  const reasons: string[] = [];

  // Engine 3: Preeclampsia & Eclampsia Threat Engine
  const isPreeclampsia = systolicBp >= 140 || diastolicBp >= 90 || urineProtein !== 'Nil';
  const isSeverePreeclampsia = systolicBp >= 160 || diastolicBp >= 110 || urineProtein === '+2' || urineProtein === '+3';

  if (isSeverePreeclampsia) {
    triggeredGuidelines.push({
      guideline: 'WHO ANC Guideline 2016 (Hypertension in Pregnancy)',
      rule: 'Systolic BP >= 160 mmHg OR Diastolic BP >= 110 mmHg OR Proteinuria >= +2',
      reason: 'Severe Preeclampsia detected with imminent eclampsia risk & active proteinuria.'
    });
    reasons.push(`Severe Hypertension: BP ${systolicBp}/${diastolicBp} mmHg exceeds critical threshold (160/110 mmHg).`);
    if (urineProtein !== 'Nil') {
      reasons.push(`Proteinuria ${urineProtein} indicating active renal involvement.`);
    }
  }

  // Engine 2: Anemia Severity & Iron Deficit Engine
  const isSevereAnemia = hbLevel < 7.0;
  const isModerateAnemia = hbLevel >= 7.0 && hbLevel < 9.0;

  if (isSevereAnemia) {
    triggeredGuidelines.push({
      guideline: 'Government of India High-Risk Pregnancy Protocol 2022',
      rule: 'Hemoglobin < 7.0 g/dL',
      reason: 'Severe Anemia Floor Breach requiring immediate tertiary hospital transfer for IV Iron / Blood transfusion.'
    });
    reasons.push(`Severe Anemia: Hemoglobin ${hbLevel} g/dL is below critical safety floor (7.0 g/dL).`);
  } else if (isModerateAnemia) {
    reasons.push(`Moderate Anemia: Hemoglobin ${hbLevel} g/dL requires parenteral IV Iron Sucrose infusion.`);
  }

  // Engine 5: Nutritional & BMI Trajectory Engine
  if (weightKg < 45.0) {
    reasons.push(`Low Maternal Weight: ${weightKg} kg indicates high risk of Intrauterine Growth Restriction (IUGR).`);
  }

  // 3. Mother Safety Score Computation (0 - 100)
  const sysDeduction = systolicBp >= 160 ? 45 : systolicBp >= 140 ? 25 : 0;
  const hbDeduction = hbLevel < 7.0 ? 55 : hbLevel < 9.0 ? 30 : hbLevel < 11.0 ? 10 : 0;
  const proteinDeduction = urineProtein === '+3' ? 20 : urineProtein === '+2' ? 15 : urineProtein === '+1' ? 5 : 0;

  const safetyScore = Math.max(5, 100 - sysDeduction - hbDeduction - proteinDeduction);
  const riskLevel = safetyScore < 40 ? 'CRITICAL' : safetyScore < 60 ? 'HIGH' : safetyScore < 80 ? 'MODERATE' : 'LOW';
  const referralPriority = safetyScore < 40 ? 'EMERGENCY' : safetyScore < 60 ? 'URGENT' : 'ROUTINE';

  // 4. Structured 5-Tier Action Plan
  const actionPlan = {
    immediateWithin30Mins:
      safetyScore < 40
        ? 'Dispatch 108 Ambulance & Lock HDU Bed at Haveri District Hospital.'
        : 'Schedule Doctor OPD Consultation at Byadgi PHC.',
    withinToday:
      safetyScore < 40
        ? 'Administer prophylactic Magnesium Sulfate protocol (Pr Pritchard regimen).'
        : 'Dispense 60 Tablets of Iron & Folic Acid (IFA) + Calcium.',
    within3Days:
      safetyScore < 40
        ? 'Complete Blood Count (CBC) & Serum Creatinine re-check.'
        : 'Repeat BP check at Sub-Center.',
    nextAncDate: new Date(Date.now() + 28 * 24 * 60 * 60 * 1000).toISOString().split('T')[0]
  };

  // 5. Engine 8: Top 3 Smart Hospital Capability Scorer
  const defaultHospitals: CandidateHospital[] = candidateHospitals.length > 0 ? candidateHospitals : [
    {
      facilityId: 'fac-dh-hav',
      facilityNameEn: 'Haveri District Hospital',
      facilityTier: 'DISTRICT_HOSPITAL',
      distanceKm: 18.2,
      travelTimeMins: 25,
      hduBedsAvailable: 4,
      bloodStock: { O_NEGATIVE: 2, O_POSITIVE: 6 }
    },
    {
      facilityId: 'fac-chc-byd',
      facilityNameEn: 'Byadgi Community Health Center',
      facilityTier: 'CHC',
      distanceKm: 4.8,
      travelTimeMins: 8,
      hduBedsAvailable: 0,
      bloodStock: {}
    },
    {
      facilityId: 'fac-phc-byd',
      facilityNameEn: 'Byadgi Primary Health Center',
      facilityTier: 'PHC',
      distanceKm: 2.4,
      travelTimeMins: 4,
      hduBedsAvailable: 0,
      bloodStock: {}
    }
  ];

  const topRankedHospitals = defaultHospitals.map((h, idx) => {
    const bedScore = h.hduBedsAvailable > 0 ? 40 : 0;
    const bloodScore = (h.bloodStock?.O_NEGATIVE || 0) > 0 ? 30 : 0;
    const tierScore = h.facilityTier === 'DISTRICT_HOSPITAL' ? 30 : 15;
    const distancePenalty = Math.min(20, h.distanceKm * 0.5);

    const capabilityScore = Math.max(10, Math.round(bedScore + bloodScore + tierScore - distancePenalty));

    return {
      rank: idx + 1,
      ...h,
      capabilityScore,
      reasons: h.hduBedsAvailable > 0
        ? [`${h.hduBedsAvailable} HDU Beds Available`, 'O-ve Blood In Stock', '24/7 Obstetrician On-Call']
        : ['Stabilization & Referral Hub Only']
    };
  }).sort((a, b) => b.capabilityScore - a.capabilityScore);

  return {
    aiVersion: 'v3.0.0-cdss',
    ruleVersion: '2026.1-WHO-GOI',
    timestamp: new Date().toISOString(),
    status: 'COMPLETED',
    safetyScore,
    riskLevel,
    dataCompletenessPercent: completenessPercent,
    predictionReliability,
    missingInputs: isCoreMissing ? ['Blood Pressure', 'Hemoglobin'] : ['Ultrasound Scan'],
    disclaimer,
    triggeredGuidelines,
    reasons,
    actionPlan,
    referralPriority,
    topRankedHospitals
  };
};
